<div class="block-press">
	<div class="center-wrapper">
		<a name="press"></a>
		<div class="clearfix">
			<a href="press/index.html" class="press-archive-button">Архив новостей</a><h2  class="block-title">Пресс-центр</h2>
		</div>
		<div class="press-list clearfix">
			<a  href="press/reportazh_lifenews_o_reforume_2014/index.html" class="press-item"><span class="pic"><img  src="/images/cms/thumbs/2915215f6e67c4a97826d2594fdde5a7.jpg" width="198" height="198" alt="" title=""></img></span><span class="date"></span><span class="title">Репортаж Lifenews о РеФоруме 2014</span><span class="text"><p>Бизнес в кризисных условиях: сокращать или вдохновлять сотрудников?<br />Стратегии управления обсуждали на РеФоруме 13-14 ноября.</p></span></a><a  href="press/reportazh_o_reforum_ot_world_business_channel/index.html" class="press-item"><span class="pic"><img  src="/images/cms/thumbs/7c2e86e192564cd51281b53b5353bdce.jpg" width="198" height="198" alt="" title=""></img></span><span class="date"></span><span class="title">Репортаж о ReForum от World Business Channel﻿</span><span class="text"><p>РеФорум: как выигрывать сердца сотрудников 2014, Москва</p>
			<p>Интервью: Александр Филатов, Алексей Марей, Юлия Рыжова, Венсан Жанти, Пётр Зайченко, Михаил Слободин, Андрей Шаронов</p></span></a><a  href="press/gendirektor_vympelkoma_rasskazal_kak_proishodit_totalnaya_perezagruzka_mobilnogo_operatora/index.html" class="press-item"><span class="pic"><img  src="/images/cms/thumbs/2b0a1f753c02b43e78b201bed3e805e9.png" width="198" height="198" alt="" title=""></img></span><span class="date"></span><span class="title">Гендиректор «Вымпелкома» рассказал, как происходит «тотальная перезагрузка» мобильного оператора</span><span class="text"><p>Михаил Слободин: &laquo;Меня наняли для ее тотальной перезагрузки. Пришлось восстанавливать нарушенные связи &ndash; с клиентами, сотрудниками и индустрией. Какая из связей главная? Бесспорно, связь с сотрудниками. Ведь они лучше знают клиентов и индустрию&raquo;.</p></span></a><a  href="press/akula_zadumalas_o_smysle/index.html" class="press-item"><span class="pic"><img  src="/images/cms/thumbs/4e919a4e825dd91ecb5f470fe3574121.png" width="198" height="198" alt="" title=""></img></span><span class="date"></span><span class="title">Акула задумалась о смысле</span><span class="text"><p>Что может заставить крупную компанию отказаться от прибыли? Правильно. Только возможность получить еще большую прибыль. И для достижения этой цели нужна целая армия &ndash; лояльных, трудолюбивых и благодарных сотрудников, которые будут идти в ногу с руководством, планомерно наращивать вес организации и усиливать ее позиции на рынке.</p></span></a>
		</div>
	</div>
</div>