<div class="block-speakers">
				<div class="center-wrapper">
					<a name="spikery"></a><h2  class="block-title">Спикеры <br />2015</h2>
					<div class="speakers-list">
						<div class="row clearfix">
							<a name="123"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#123" href="spikery/bo_inge/indexc2d0.html"><span class="speakers-userpic"><img  src="/images/cms/thumbs/96517adeb5bdf6339ee28f9299dbe59a.png" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Бу Инге Андерссон</span><span class="speakers-item-post"><p>Президент ОАО «АВТОВАЗ»</p></span></span></a><a name="/spikery/hutmacher/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/hutmacher/" href="spikery/hutmacher/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/616bba797837c9948c6d36d4d5911a52.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Хайко Хутмахер</span><span class="speakers-item-post"><p>Вице-президент «METRO GROUP» Германия. Бренды: Metro C&amp;C, Real, Media Saturn, Galeria Kaufhof </p></span></span></a><a name="/spikery/olga_pleshakova/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/olga_pleshakova/" href="spikery/olga_pleshakova/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/bb2d0778cd7764f956ab0032fc43bf57.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Ольга Плешакова</span><span class="speakers-item-post"><p>Генеральный директор «ТРАНСАЭРО»</p></span></span></a><a name="/spikery/marley/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/marley/" href="spikery/marley/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/634848bb0bd12c307adbd66efea3366e.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Адриан Марлей</span><span class="speakers-item-post"><p>Генеральный директор «DHL» в СНГ и юго-восточной Европе</p></span></span></a><a name="/spikery/e_serebryanikova/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/e_serebryanikova/" href="spikery/e_serebryanikova/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/02c58031ba71e4076b77dc93dd861e72.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Екатерина Серебреникова</span><span class="speakers-item-post"><p>Заместитель генерального директора по кадровым ресурсам группы «ИЛИМ»</p></span></span></a>
						</div>
						<div class="row clearfix">
							<a name="/spikery/johannes_tolay/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/johannes_tolay/" href="spikery/johannes_tolay/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/aa0b29141b53c742d6f05b3096c649db.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Йоханнес Толай</span><span class="speakers-item-post"><p>Генеральный директор сети гипермаркетов «GLOBUS» в России</p></span></span></a><a name="/spikery/ninell_sobiecka/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/ninell_sobiecka/" href="spikery/ninell_sobiecka/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/34820d4cfaecee37be2b2ce6b0890023.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Нинелль Собиеcка</span><span class="speakers-item-post"><p>Генеральный директор сегмента Cosmétique Active «L’OREAL»</p></span></span></a><a name="/spikery/tigran_buniatyan/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/tigran_buniatyan/" href="spikery/tigran_buniatyan/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/be641de4f04a66aaf1b9f31dc351d2c8.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Тигран Буниатян</span><span class="speakers-item-post"><p>Основатель и генеральный директор сети «КОФЕЙНАЯ КАНТАТА»</p></span></span></a><a name="/spikery/g_makarov/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/g_makarov/" href="spikery/g_makarov/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/161fc72ef4292eb65f2b9f4f1667a45f.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Георгий Макаров</span><span class="speakers-item-post"><p>Генеральный директор «MARS» сегмент Food</p></span></span></a><a name="/spikery/edvard_stanoh/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/edvard_stanoh/" href="spikery/edvard_stanoh/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/72dcb4ba0969fb50dddd11837b50d1a7.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Эдвард Станох</span><span class="speakers-item-post"><p>Управляющий партнер «AON HEWITT» в Восточной Европе </p></span></span></a>
						</div>
						<div class="row clearfix">
							<a name="/spikery/iskandar_bakhtiyarov/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/iskandar_bakhtiyarov/" href="spikery/iskandar_bakhtiyarov/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/08aefadad53efa454bfab37b0926f2de.jpg" width="234" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Искандар Бахтияров</span><span class="speakers-item-post"><p>Основатель и генеральный директор компании «УФАНЕТ»</p></span></span></a><a name="/spikery/s_shilov/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/s_shilov/" href="spikery/s_shilov/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/cf268a629bebad03f56a50b80fa5df9e.png" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Сергей Шилов</span><span class="speakers-item-post"><p>Управляющий партнер и основатель «AT CONSULTING»</p></span></span></a><a name="/spikery/larissa_h/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/larissa_h/" href="spikery/larissa_h/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/5eff82d8a4357b5647a4fd5271abedd4.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Лариса Халлефорс</span><span class="speakers-item-post"><p>Директор по работе с клиентами, старший консультант «TNS SIFO» Sweden</p></span></span></a><a name="/spikery/oscar_orenifier/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/oscar_orenifier/" href="spikery/oscar_orenifier/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/ec0107f1ec55f63e81caa715653220b5.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Оскар Бренифье</span><span class="speakers-item-post"><p>Доктор философии</p></span></span></a><a name="/spikery/arsen_ryabuha/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery/arsen_ryabuha/" href="spikery/arsen_ryabuha/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/63eddc3190170a726193f6a4e16ed4bc.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Арсен Рябуха</span><span class="speakers-item-post"><p>Старший-тренер, коуч «BUSINESS RELATIONS»</p></span></span></a>
						</div>
					</div>
				</div>
			</div>
			<!--
			<div class="block-speakers">
				<div class="center-wrapper">
					<a name="spikery_fav"></a><h2  class="block-title">Спикеры рефорум<br />2013-2014</h2>
					<div class="speakers-list">
						<div class="row clearfix">
							<a name="/spikery_fav/dzhenn_lim1/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery_fav/dzhenn_lim1/" href="spikery_fav/dzhenn_lim1/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/324fee9e8304094eb59c1ac8e9baf648.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Дженн Лим</span><span class="speakers-item-post"><p>Zappos.com, консультант/ Delivering Happiness, CEO</p></span></span></a><a name="/spikery_fav/mihaj_chiksentmihaji2/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery_fav/mihaj_chiksentmihaji2/" href="spikery_fav/mihaj_chiksentmihaji2/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/0e13a2ad65e9ea92c3dabf46ade344a0.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Михай Чиксентмихайи</span><span class="speakers-item-post"><p>Чикагский университет, бывший декан факультета психологии</p></span></span></a><a name="/spikery_fav/aleksej_marej/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery_fav/aleksej_marej/" href="spikery_fav/aleksej_marej/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/2c5f87d41c417263670c374a81a934a5.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Алексей Марей</span><span class="speakers-item-post"><p>СЕО Альфа-Банк</p></span></span></a><a name="/spikery_fav/radzhendra_sisodia1/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery_fav/radzhendra_sisodia1/" href="spikery_fav/radzhendra_sisodia1/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/5165cdccd8f3058df20b450bbb16bb8f.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Раджендра Сисодиа —</span><span class="speakers-item-post"><p>Babson College, профессор глобального бизнеса</p></span></span></a><a name="/spikery_fav/maksim_nogotkov1/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery_fav/maksim_nogotkov1/" href="spikery_fav/maksim_nogotkov1/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/a35a226fcf4cd7089d77c675b26179b7.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Максим Ноготков </span><span class="speakers-item-post"><p>Предприниматель, президент Группы компаний Связной</p></span></span></a>
						</div>
						<div class="row clearfix">
							<a name="/spikery_fav/boris_bobrovnikov/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery_fav/boris_bobrovnikov/" href="spikery_fav/boris_bobrovnikov/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/c0044b08b20db3284e0ae3f667b2104a.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Борис Бобровников</span><span class="speakers-item-post"><p>Генеральный директор компании КРОК </p></span></span></a><a name="/spikery_fav/mihail_slobodin/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery_fav/mihail_slobodin/" href="spikery_fav/mihail_slobodin/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/6e0dd09a7367859b0bcc250c472821ab.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Михаил Слободин</span><span class="speakers-item-post"><p>Генеральный директор ОАО «ВымпелКом»</p></span></span></a><a name="/spikery_fav/vladislav_solodkij/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery_fav/vladislav_solodkij/" href="spikery_fav/vladislav_solodkij/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/2700254994960af0541dec6a89175ce3.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Владислав Солодкий</span><span class="speakers-item-post"><p>Управляющий партнер венчурного фонда LIFE.SREDA</p></span></span></a><a name="/spikery_fav/aleksandr_filatov/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery_fav/aleksandr_filatov/" href="spikery_fav/aleksandr_filatov/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/e295ef8899700a200c1a7413eccf43ff.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Александр Филатов</span><span class="speakers-item-post"><p>Генеральный директор Arkley Capital</p></span></span></a><a name="/spikery_fav/andres_graziosi/"></a><a  class="speakers-item ajaxBox cboxElement" data-href="#/spikery_fav/andres_graziosi/" href="spikery_fav/andres_graziosi/indexc2d0.html?ajax=1"><span class="speakers-userpic"><img  src="/images/cms/thumbs/67802ba43224bdc13eb4213ab5a83f6b.jpg" width="235" height="235" alt="" title=""></img></span><span class="speakers-item-text"><span class="speakers-item-name">Андрес Грациоси</span><span class="speakers-item-post"><p>Управляющий директор компании «Новартис Фарма» в России</p></span></span></a>
						</div>
					</div>
				</div>
			</div>
			-->