<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");
$APPLICATION->SetTitle("");?><?$APPLICATION->IncludeComponent(
	"bitrix:player",
	"",
	Array(
		"PLAYER_TYPE" => "flv",
		"USE_PLAYLIST" => "N",
		"PATH" => "/video/mc_0216/intro.flv",
		"PLAYLIST_DIALOG" => "",
		"PROVIDER" => "video",
		"STREAMER" => "",
		"WIDTH" => "900",
		"HEIGHT" => "400",
		"PREVIEW" => "",
		"FILE_TITLE" => "Мастерские каникулы",
		"FILE_DURATION" => "3000",
		"FILE_AUTHOR" => "",
		"FILE_DATE" => "01.08.2010",
		"FILE_DESCRIPTION" => "Мастерские каникулы",
		"SKIN_PATH" => "/bitrix/components/bitrix/player/mediaplayer/skins",
		"SKIN" => "glow.zip",
		"CONTROLBAR" => "bottom",
		"WMODE" => "transparent",
		"PLAYLIST" => "right",
		"PLAYLIST_SIZE" => "180",
		"LOGO" => "",
		"LOGO_LINK" => "",
		"LOGO_POSITION" => "bottom-left",
		"PLUGINS" => array("",""),
		"PLUGINS_TWEETIT-1" => "tweetit.link=",
		"PLUGINS_FBIT-1" => "fbit.link=",
		"ADDITIONAL_FLASHVARS" => "",
		"WMODE_WMV" => "window",
		"SHOW_CONTROLS" => "Y",
		"PLAYLIST_TYPE" => "auto",
		"PLAYLIST_PREVIEW_WIDTH" => "64",
		"PLAYLIST_PREVIEW_HEIGHT" => "48",
		"SHOW_DIGITS" => "Y",
		"CONTROLS_BGCOLOR" => "FFFFFF",
		"CONTROLS_COLOR" => "000000",
		"CONTROLS_OVER_COLOR" => "000000",
		"SCREEN_COLOR" => "000000",
		"AUTOSTART" => "N",
		"REPEAT" => "none",
		"VOLUME" => "90",
		"MUTE" => "N",
		"HIGH_QUALITY" => "Y",
		"SHUFFLE" => "N",
		"START_ITEM" => "1",
		"ADVANCED_MODE_SETTINGS" => "Y",
		"PLAYER_ID" => "",
		"BUFFER_LENGTH" => "10",
		"DOWNLOAD_LINK" => "",
		"DOWNLOAD_LINK_TARGET" => "_self",
		"ADDITIONAL_WMVVARS" => "",
		"ALLOW_SWF" => "Y",
		"COMPONENT_TEMPLATE" => ".default"
	)
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/epilog_after.php");?>