<?
$aMenuLinks = Array(
/*
	Array(
		"Резюме на сайте", 
		"/about/", 
		Array(), 
		Array(), 
		"" 
	),
	*/
	Array(
		"hh.ru", 
		"http://hh.ru/resume/ac6d402fff021306120039ed1f4a5a354d695a", 
		Array(), 
		Array("target"=>"_blank"), 
		"" 
	),
	Array(
		"SuperJob.ru", 
		"https://www.superjob.ru/resume/programmist-bitriks-27851644.html", 
		Array(), 
		Array("target"=>"_blank"), 
		"" 
	),
	Array(
		"job-mo.ru", 
		"http://www.job-mo.ru/res2542688.html", 
		Array(), 
		Array("target"=>"_blank"), 
		"" 
	),
	Array(
		"rabota.ru", 
		"https://schelkovo.rabota.ru/resume9891540.html", 
		Array(), 
		Array("target"=>"_blank"), 
		"" 
	)
);
?>